---
abstract: Perl extension to test methods for warnings
author:
  - 'Janek Schleicher <bigj@kamelfreund.de>'
build_requires:
  File::Spec: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
keywords:
  - testing
  - warnings
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Warn
provides:
  Test::Warn:
    file: Warn.pm
    version: '0.23'
requires:
  Carp: 1.22
  Sub::Uplevel: 0.12
  Test::Builder: 0.13
  Test::Builder::Tester: 1.02
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/hanfried/test-warn
version: 0.35
